### ISSUE TITLE
do you  support the use of functions in query statements？

### ISSUE THREAD

**Issue by fellyvon** [vincentrussell/sql-to-mongo-db-query-converter#45]
We have a requirement that is aggregated on a monthly basis，can  it be supported? the code  is as follows:

`select   date(ci.created_at,'YYY-MM')  as x, count(cr.check_item_id) as y 
from check_record cr 
join check_item ci on ci._id = OID(cr.check_item_id) 
where cr.project_id=358 
and cr.created_at > {ts '2020-11-10 00:00:00'} 
and cr.created_at < {ts '2020-12-01 00:00:00'} 
group by date(ci.created_at,'YYY-MM') `

thanks

**Comment by vincentrussell** [comment]
No.  I don't think this is currently supported, but what would you expect the mongo translation of this to be?

**Comment by lfeagan** [comment]
Hi Vincent,
Thanks for this great work. I also need functions in my project clause. I hacked a bit to get it working in a way that meets my needs. Below is an example of how I have it working:

```
select id,sin(temperature) as temp from GasRecordV1;

******Mongo Query:*********

db.GasRecordV1.aggregate([{
  "$project": {
    "_id": 0,
    "id": 1,
    "temp": {
      "$sin": "$temperature"
    }
  }
}])
```

All of the unit tests pass, but the biggest thing I am not sure about right now is how I just brutally chopped off the validation for all select items being a column around line 140 of Query Converter (line may have changed due to other changes). I also borrowed the recurse function code from the WhereClauseProcessor. And re-used the getNormalizedValue, but manually tack on a $ if the type is a column so the expression works.

Happy to submit a PR if interested.

Thanks!
